### ISSUE TITLE
[Bug]: AssertionError: "<package>.wasm" is not a valid WASI executable

### ISSUE THREAD

**Issue by wellcaffeinated** [wasmerio/wasmer-pack#130]
### What happened?

Hi. I'm trying to use wapm and wasm-bindgen to create js/python bindings for a library i'm writing, and _it works in node.js_, but when i try to load the bindings in python i get this:

```py
>>> from spdcalc import bindings
>>> spdc = bindings.spdcalc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wellcaffeinated/Documents/github/spdcalc/wasm/py/spdcalc/bindings/__init__.py", line 56, in spdcalc
    assert version is not None, f'"{filename}" is not a valid WASI executable'
AssertionError: "spdcalc/spdcalc.wasm" is not a valid WASI executable
```

My Cargo.toml contains the following meta:

```toml
[package.metadata.wapm]
namespace = "wellcaffeinated"  # Replace this with your WAPM username
abi = "wasi"
bindings = { wit-bindgen = "0.2.0", wit-exports = "spdcalc.wai" }
```

and I'm using the following commands to build it:

```sh
cargo wapm -d --out-dir ./wapm
wasmer-pack python ./wapm --out-dir ./py
```

Any help would be appreciated!

### Wasmer Pack Version

wasmer-pack-cli 0.7.0

### How were you using wasmer-pack?

the command-line

**Comment by wellcaffeinated** [comment]
More information:
This error goes away when i remove the following:
```wai
resource foo {
  test: func() -> float32
}
```

any resource implementing seems to give this error
